if( NOT TARGET Cinder-Bullet3D )
	get_filename_component( CINDER_BULLET3D_SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../src" ABSOLUTE )
	get_filename_component( CINDER_PATH "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE )

	list( APPEND CINDER_BULLET3D_SOURCES
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/BulletContext.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/Common.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintBase.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintConeTwist.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintGeneric6Dof.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintHinge.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintPoint2Point.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhyObjCharacterController.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhyObjTriggerVol.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhysicsDebugRenderable.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/RigidBody.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/SoftBody.cpp

		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/BulletContext.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/Common.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintBase.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintConeTwist.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintGeneric6Dof.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintHinge.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/ConstraintPoint2Point.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/MotionState.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhyObjCharacterController.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhyObjTriggerVol.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/PhysicsDebugRenderable.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/RigidBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/Cinder-Bullet3D/SoftBody.h


		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/btBulletCollisionCommon.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/btBulletDynamicsCommon.h

		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDMath.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDConfigBuiltin.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDConfig.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDErrorMessages.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDConfigEigen.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/MultiBodyTree.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/MultiBodyTree.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/IDMath.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/MultiBodyTreeImpl.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/MultiBodyTreeImpl.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/IDEigenInterface.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/IDMatVec.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/IDLinearMathInterface.hpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletInverseDynamics/details/MultiBodyTreeInitCache.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/shared/b3ConvertConstraint4.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/shared/b3Inertia.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/shared/b3IntegrateTransforms.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/shared/b3ContactConstraint4.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/clew/clew.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/clew/clew.c
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/b3Config.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGearConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGearConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btHinge2Constraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btConstraintSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btJacobianEntry.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSolverBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolverMt.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btHingeConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btContactConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btTypedConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btFixedConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btBatchedConstraints.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSolverConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btBatchedConstraints.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btContactConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSliderConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Vehicle/btRaycastVehicle.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Vehicle/btVehicleRaycaster.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Vehicle/btWheelInfo.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Vehicle/btWheelInfo.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Character/btKinematicCharacterController.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Character/btKinematicCharacterController.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Character/btCharacterControllerInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btRigidBody.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btActionInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btRigidBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btSimulationIslandManagerMt.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorldMt.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodySliderConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyGearConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyFixedConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyConstraint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyLink.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBodyJointFeedback.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/Featherstone/btMultiBody.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btLemkeSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btMLCPSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btDantzigSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btDantzigLCP.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btPATHSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btPointCollector.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btMprPenetration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/NarrowPhaseCollision/btConvexCast.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btTriangleShapeEx.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btContactProcessing.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_bitset.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btBoxCollision.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btTriangleShapeEx.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactBvh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_memory.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGenericPoolAllocator.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_array.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_box_set.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_clip_polygon.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btContactProcessing.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_box_set.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_tri_collision.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGeometryOperations.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactBvhStructs.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_radixsort.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_tri_collision.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactMassUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactQuantizedBvhStructs.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_box_collision.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btCompoundFromGimpact.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btQuantization.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_hash_table.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_contact.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGenericPoolAllocator.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_basic_geometry_operations.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_geometry.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_math.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btClipPolygon.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_geom_types.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btContactProcessingStructs.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_memory.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_linear_math.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/gim_contact.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/Gimpact/btGImpactBvh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDispatcher.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDispatcher.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDbvt.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDbvt.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btAxisSweep3Internal.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btAxisSweep3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btUnionFind.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionConfiguration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionDispatcherMt.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/SphereTriangleDetector.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSimulationIslandManager.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionObject.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btGhostObject.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btManifoldResult.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionObject.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btUnionFind.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBoxBoxDetector.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btGhostObject.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btManifoldResult.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCylinderShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTetrahedronShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBox2dShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btSdfCollisionShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConeShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexPolyhedron.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvex2dShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btShapeHull.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMultiSphereShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleBuffer.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCylinderShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCompoundShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCollisionShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btOptimizedBvh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleCallback.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleMesh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btEmptyShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCollisionShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMiniSDF.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBoxShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleInfoMap.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btStaticPlaneShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexInternalShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBoxShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMaterial.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConeShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCollisionMargin.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btShapeHull.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexHullShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConcaveShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexInternalShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btStridingMeshInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleCallback.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConcaveShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleMeshShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMiniSDF.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleBuffer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleMesh.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btOptimizedBvh.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvex2dShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btSdfCollisionShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexHullShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btBox2dShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btUniformScalingShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCapsuleShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btMultiSphereShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btSphereShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCompoundShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btTetrahedronShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btSphereShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btEmptyShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btUniformScalingShape.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletCollision/CollisionShapes/btCapsuleShape.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3File.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Defines.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3File.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/b3Common.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyHelpers.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btDefaultSoftBodySolver.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodySolvers.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBody.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftRigidDynamicsWorld.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyHelpers.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyData.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBody.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftRigidDynamicsWorld.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btDefaultSoftBodySolver.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftRigidCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodySolverVertexBuffer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftSoftCollisionAlgorithm.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSoftBodyInternals.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/BulletSoftBody/btSparseSDF.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btGeometryUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btQuadWord.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btStackAlloc.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btHashMap.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btMotionState.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btGeometryUtil.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btMatrix3x3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btSerializer64.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btVector3.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btTransformUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btRandom.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btMinMax.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btConvexHull.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btScalar.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btDefaultMotionState.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btQuickprof.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btAlignedAllocator.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btQuickprof.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btGrahamScan2dConvexHull.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btPolarDecomposition.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btList.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btVector3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btConvexHull.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btMatrixX.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btTransform.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btAlignedAllocator.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btSerializer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btThreads.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btAlignedObjectArray.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btQuaternion.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btCpuFeatureUtility.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btThreads.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btSerializer.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btSpatialAlgebra.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btConvexHullComputer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btAabbUtil2.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btConvexHullComputer.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btPoolAllocator.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btIDebugDraw.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/btPolarDecomposition.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/TaskScheduler/btThreadSupportWin32.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/TaskScheduler/btThreadSupportPosix.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/TaskScheduler/btThreadSupportInterface.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/LinearMath/TaskScheduler/btTaskScheduler.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3GrahamScan2dConvexHull.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3ConvexHullComputer.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3GeometryUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3GeometryUtil.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3AabbUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Geometry/b3ConvexHullComputer.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Vector3.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Logging.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3AlignedAllocator.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Matrix3x3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Vector3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3AlignedObjectArray.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Scalar.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3ResizablePool.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Logging.cpp
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3PoolAllocator.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3CommandLineArgs.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3MinMax.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3QuadWord.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3FileUtils.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3AlignedAllocator.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3StackAlloc.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Random.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3TransformUtil.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Transform.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3Quaternion.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/b3HashMap.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3Float4.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3PlatformDefinitions.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3Int4.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3Mat3x3.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3Quat.h
		${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src/Bullet3Common/shared/b3Int2.h


	)

	add_library( Cinder-Bullet3D ${CINDER_BULLET3D_SOURCES} )

	target_include_directories( Cinder-Bullet3D PUBLIC "${CINDER_BULLET3D_SOURCE_PATH}" )

	target_include_directories( Cinder-Bullet3D SYSTEM BEFORE PUBLIC "${CINDER_BULLET3D_SOURCE_PATH}/bullet3/src" )
	target_include_directories( Cinder-Bullet3D SYSTEM BEFORE PUBLIC "${CINDER_BULLET3D_SOURCE_PATH}/include/Cinder-Bullet3D" )

	target_include_directories( Cinder-Bullet3D SYSTEM BEFORE PUBLIC "${CINDER_PATH}/include" )

	if( NOT TARGET cinder )
		    include( "${CINDER_PATH}/proj/cmake/configure.cmake" )
		    find_package( cinder REQUIRED PATHS
		        "${CINDER_PATH}/${CINDER_LIB_DIRECTORY}"
		        "$ENV{CINDER_PATH}/${CINDER_LIB_DIRECTORY}" )
	endif()
	target_link_libraries( Cinder-Bullet3D PRIVATE cinder )


endif()